[package]
name = "noisegen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
image = "0.25.5"
rand = "0.9.0"
rand_distr = "0.5.1"

candle-core = { git = "https://github.com/aifx-art/candle.git", branch = "wip2" }
#candle-datasets = { git = "https://github.com/aifx-art/candle.git", branch = "wip", optional=true}
candle-nn = { git = "https://github.com/aifx-art/candle.git", optional = false, branch = "wip2" }
candle-transformers = { git = "https://github.com/aifx-art/candle.git", optional = false, branch = "wip2" }
candle-flash-attn = { git = "https://github.com/aifx-art/candle.git", branch = "wip2", optional = true }
